[package]
name = "goscript-playground"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"


[dependencies.goscript-engine]
path = "../../goscript/engine"
version = "0.1.0" 
features = ["read_zip", "wasm"]